### ISSUE TITLE
About saving results

### ISSUE THREAD

**Issue by alevangel** [Yuki-11/CSSR#3]
Hi.
I'm trying to retrain the SS_SR, but during training and after it I won't get the results saved nowhere. 
I'm using the cfg parameter in the yaml file "OUTPUT_DIR", and the --output_dirname parameter.

There is a bug somewhere on this branch or I'm doing something wrong?

On Colab:
`!python train.py --config_file "./config/exp2/config_CSSR_SR-SS.yaml" --num_workers 2 --num_gpus 1 --output_dirname "/content/CSSR/output/" --save_step 250`

**Comment by ashutoshbk** [comment]
hey do you able to get result for new images not with test datasets using pretrained model?

**Comment by Yuki-11** [comment]
I apologize for the delay in replying. 

Since the model is saved in this part of trainer.py, it is possible that the debug flag is set, the save_step check failed, or the size of the data loader is 0 and the for loop of training is not running. We would appreciate it if you could check this.

![image](https://github.com/Yuki-11/CSSR/assets/62691917/03428492-872a-4c65-9ecc-2eb45d4fa4e7)
